server:
  port: 8080
  servlet:
    context-path: /money-monitor-backend/rest

spring:
  application:
    name: money-monitor-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/MoneyMonitor
    username: postgres
    password: Leonidas-7
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_schema: "MoneyMonitor"
        show_sql: true
logging:
  level:
    root: info
