spring:
  application:
    name: money-monitor-backend
  datasource:
    url: ${DATASOURCE_HOST:jdbc:sqlserver:localhost\SQLEXPRESS:1433;DatabaseName=MoneyMonitor;Trusted_Connection=True}
    username: ${DATASOURCE_USERNAME:LEONARDOG15\leona}
    password: ${DATASOURCE_PASSWORD:}

server:
  port: 8080
  servlet:
    context-path: /money-monitor-backend/rest
